# Generated by Django 2.0.3 on 2018-04-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('recommended_age_start', models.IntegerField()),
                ('recommended_age_stop', models.IntegerField()),
                ('dosage_per_kg', models.FloatField()),
                ('grace_period_days', models.IntegerField()),
                ('instructions', models.TextField()),
                ('quantity_unit', models.CharField(default='ml', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDiscard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(max_length=100)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('recovery_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('stop_date', models.DateField(null=True)),
                ('comments', models.TextField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='surgery',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.Treatment'),
        ),
        migrations.AddField(
            model_name='medicationapplication',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.Treatment'),
        ),
    ]
