# Generated by Django 2.0.3 on 2018-04-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_feeding_age', models.IntegerField()),
                ('stop_feeding_age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='feedentry',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeding.FeedType'),
        ),
    ]
