# Generated by Django 2.0.3 on 2018-03-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('cause', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalFarmExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('destination', models.CharField(default='Unknown', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalFlockExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('number_of_animals', models.IntegerField()),
                ('farm_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.AnimalFarmExit')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=250)),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flocks.AnimalDeath')),
                ('exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flocks.AnimalFlockExit')),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_weight', models.FloatField()),
                ('number_of_animals', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animalseparation',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock'),
        ),
        migrations.AddField(
            model_name='animalflockexit',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock'),
        ),
        migrations.AddField(
            model_name='animaldeath',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock'),
        ),
    ]
